<?php $this->headTitle ($this->translate('Manage collections'))?>
<?php echo $this->render('menu.phtml');?>
<h2><?php echo $this->translate('Manage collections')?></h2>
<p><a href="<?php echo $this->url(array('action' => 'edit'))?>"><?php echo $this->translate('Create a new Collection')?>&raquo;</a></p>
<?php if (!count($this->collections)):?>
<div class="note">
	<p><?php echo $this->translate('No collections to manage.')?></p>
</div>
<?php else:?>
<p><?php echo $this->translate('Click on a code to edit the collection.')?></p>
<table class="collections">
	<thead>
		<tr>
			<th>#</th>
			<th><?php echo $this->translate('Code')?></th>
			<th><?php echo $this->translate('Title')?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->collections as $i => $collection):?>
		<tr class="<?php echo $i % 2 ? 'even' : 'uneven'?>">
			<th scope="row"><?php echo $i+1?></th>
			<td><a href="<?php echo $this->url(array('action' => 'edit', 'collection' => $collection->code))?>"><?php echo $collection->code?></a></td>
			<td><?php echo $collection->dc_title?></td>
		</tr>
		<?php endforeach?>
	</tbody>
</table>
<?php endif?>

