<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php if ($this->user->id):?>
<?php $this->headTitle($this->translate('Edit user'))?>
<?php else:?>
<?php $this->headTitle($this->translate('Create user'))?>
<?php endif?>

<?php echo $this->user->getForm()->setAction($this->url(array('action' => 'save')))?>

<?php 
//code to inject a random API key
$serverUrl = $this->serverUrl();
$js = <<<JS
function randomString(string_length) {
	var chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";
	var randomstring = '';
	for (var i=0; i<string_length; i++) {
		var rnum = Math.floor(Math.random() * chars.length);
		randomstring += chars.substring(rnum,rnum+1);
	}
	return randomstring;
}

window.addEvent('load', function(){
	Asset.image('{$serverUrl}/assets/images/keygen.png', {
	    title: 'Generate random API key',
	    styles: {'margin-left': 10, 'cursor' : 'pointer'},
	    events: {
	    	click: function() {
	    		\$('apikey').set('value', randomString(16));
	    	}
	    },
	    onLoad: function() {
	    	this.inject(\$('apikey'), 'after');
	    }
	});
	
	
});
JS;
$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, $js);
?>