<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Manage users'))?>

<?php if (OpenSKOS_Db_Table_Users::fromIdentity()->isAllowed('editor.users', 'manage')): ?>
	<p><a href="<?php echo $this->url(array('action' => 'edit'))?>"><?php echo $this->translate('Create a new user')?>&raquo;</a></p>
<?php endif?>

<?php if (!count($this->users)):?>
<div class="note">
	<p><?php echo $this->translate('No users to manage.')?></p>
</div>
<?php else:?>
<p><?php echo $this->translate('Click on a name to edit the user.')?></p>
<table class="users">
	<thead>
		<tr>
			<th>#</th>
			<th><?php echo $this->translate('Name')?></th>
			<th><?php echo $this->translate('E-mail')?></th>
			<th><?php echo $this->translate('Role')?></th>
			<th><?php echo $this->translate('Usertype')?></th>
			<th><?php echo $this->translate('API key')?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->users as $i => $user):?>
		<tr class="<?php echo $i % 2 ? 'even' : 'uneven'?>">
			<th scope="row"><?php echo $i+1?></th>
			<td>
			<?php if (OpenSKOS_Db_Table_Users::fromIdentity()->isAllowed('editor.users', 'manage')): ?>
				<a href="<?php echo $this->url(array('action' => 'edit', 'user' => $user->id))?>"><?php echo $user->name?></a>
			<?php else: ?>
				<?php echo $user->name?>
			<?php endif ?>
			</td>
			<td><?php echo $user->email?></td>
			<td><?php echo $this->translate($user->role)?></td>
			<td><?php echo $this->translate($user->type)?></td>
			<td><?php echo $user->apikey?></td>
		</tr>
		<?php endforeach?>
	</tbody>
</table>
<?php endif?>
