<?php
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'?>
<?php
$namespaces = array('rdf');
ob_start();
foreach ($this->response['response']['docs'] as $doc) {
	echo $doc['xml'];
	$namespaces = array_merge($namespaces, $doc['xmlns']);
}
$xml = ob_get_contents();
ob_end_clean();
$namespaces = array_unique($namespaces);
?>
<rdf:RDF
	<?php 
	foreach ($namespaces as $prefix):
		printf('xmlns:%s="%s" ', $prefix, $this->namespaces[$prefix]);
	endforeach
	?>
	xmlns:openskos="http://openskos.org/xmlns#"
	<?php foreach ($this->response['response'] as $key => $var): if ($key == 'docs') continue;?>
	openskos:<?php echo $key?>="<?php echo $var?>"
	<?php endforeach?>
>
<?php echo $xml?>
</rdf:RDF>