<?php echo '<?xml version="1.0" encoding="UTF-8"?>'?>
<?php
$namespaces = array('rdf');
ob_start();
foreach ($this->response['response']['docs'] as $doc) {
	echo $doc['xml'];
	$namespaces = array_merge($namespaces, $doc['xmlns']);
}
$xml = ob_get_contents();
ob_end_clean();
$namespaces = array_unique($namespaces);
?>
<rdf:RDF
	<?php 
	foreach ($namespaces as $prefix):
		printf('xmlns:%s="%s" ', $prefix, $this->namespaces[$prefix]);
	endforeach
	?>
	xmlns:openskos="http://openskos.org/xmlns#"
	<?php foreach ($this->response['response'] as $key => $var): if ($key == 'docs') continue;?>
	openskos:<?php echo $key?>="<?php echo $var?>"
	<?php endforeach?>
>
<?php echo $xml?>
</rdf:RDF>