<?php $this->headTitle ($this->translate('Manage institution'))?>
<?php echo $this->render('menu.phtml');?>
<h2><?php echo $this->translate('Manage institution')?></h2>
<div class="clear">
	<div id="collection-form">
		<?php echo $this->tenant->getForm()?>
	</div>
	<div id="collection-stats" class="box">
		<p><?php echo $this->translate('You can share this information via the OpenSKOS API')?>:</p>
		<ul>
			<li><a href="<?php echo $this->url(array('module' => 'api', 'controller'=>'institutions', 'id' => $this->tenant->code), 'rest', true)?>.rdf">in RDF (VCard)</a></li>
			<li><a href="<?php echo $this->url(array('module' => 'api', 'controller'=>'institutions', 'id' => $this->tenant->code), 'rest', true)?>.html">in HTML</a></li>
			<li><a href="<?php echo $this->url(array('module' => 'api', 'controller'=>'institutions', 'id' => $this->tenant->code), 'rest', true)?>.json">in JSON</a></li>
		</ul>
	</div>
</div>
	