<?php $this->headTitle ($this->collection->dc_title)?>
<h2><?php echo $this->collection->dc_title?></h2>
<div class="clear">
	<div id="collection-form">
<p class="dc_creator"><?echo $this->translate('Institution')?>: 
	<em><a href="<?php echo $this->url(array('controller'=>'institutions', 'id' => $this->tenant->code))?>.html"><?php echo $this->tenant->name?></a></em></p>
	<?php if ($this->collection->dc_description):?>
		<p class="dc_description"><?php echo nl2br($this->collection->dc_description, true)?></p>
	<?php endif?>
	<?php if ($this->collection->website):?>
		<p class="website"><?php echo $this->translate('See')?> <a rel="external" href="<?php echo $this->collection->website?>"><?php echo $this->collection->website?></a></p>
	<?php endif?>
	<?php if ($this->collection->license_name && $this->collection->license_url):?>
		<p class="licence"><?php echo $this->translate('License')?>: <a rel="external" href="<?php echo $this->collection->license_url?>"><?php echo $this->collection->license_name?></a></p>
	<?php elseif ($this->collection->license_name):?>
		<p class="licence"><?php echo $this->translate('License')?>: <?php echo $this->collection->license_name?></p>
	<?php elseif ($this->collection->license_url):?>
		<p class="licence"><?php echo $this->translate('License')?>: <a rel="external" href="<?php echo $this->collection->license_url?>"><?php echo $this->collection->license_url?></a></p>
	<?php endif?>
	</div>
	<div id="collection-stats" class="box">
		<h3>SKOS Concepts per class:</h3>
		<ul>
			<?php foreach ($this->collection->getClasses() as $class => $count):?>
			<li><?php echo OpenSKOS_Rdf_Parser::$namespaces['skos'].$class?>: <?php echo number_format($count, 0)?></li>
			<?php endforeach?>
		</ul>
	</div>
</div>
<h3>Alternative formats</h3>
<ul>
	<li><a class="json" href="<?php echo str_replace('.html', '.json', $this->url())?>">JSON</a></li>
	<li><a class="rdf" href="<?php echo str_replace('.html', '.rdf', $this->url())?>">RDF</a></li>
</ul>
