<?php
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle ($this->collection->dc_title)?>
<h2><?php echo $this->collection->dc_title?></h2>
<div class="clear">
	<div id="collection-form">
<dl>
	<dt><?php echo $this->translate('Institution')?>:</dt>
	<dd><a href="<?php echo $this->url(array('controller'=>'institutions', 'id' => $this->tenant->code))?>.html"><?php echo $this->tenant->name?></a></dd>

	<?php if ($this->collection->dc_description):?>
	<dt><?php echo $this->translate('Description')?>:</dt>
	<dd><?php echo nl2br($this->collection->dc_description, true)?></dd>
	<?php endif?>


	<?php if ($this->collection->website):?>
	<dt><?php echo $this->translate('Website')?>:</dt>
	<dd><a rel="external" href="<?php echo $this->collection->website?>"><?php echo $this->collection->website?></a></dd>
	<?php endif?>

	<?php if ($this->collection->license_name && $this->collection->license_url):?>
	<dt><?php echo $this->translate('License')?>:</dt>
	<dd><a rel="external" href="<?php echo $this->collection->license_url?>"><?php echo $this->collection->license_name?></a></dd>
	<?php elseif ($this->collection->license_name):?>
	<dt><?php echo $this->translate('License')?>:</dt>
	<dd><?php echo $this->collection->license_name?></dd>
	<?php elseif ($this->collection->license_url):?>
	<dt><?php echo $this->translate('License')?>:</dt>
	<dd><a rel="external" href="<?php echo $this->collection->license_url?>"><?php echo $this->collection->license_url?></a></dd>
	<?php endif?>
</dl>

<h3><?php echo $this->translate('ConceptSchemes')?></h3>
<ul>
	<?php foreach ($this->collection->getConceptSchemes() as $conceptScheme):?>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'concept', 'id' => $conceptScheme['uuid']), 'rest')?>.html">
			<?php echo $conceptScheme['uri']?>
		</a>
	</li>
	<?php endforeach?>
</ul>
<?php ?>

	</div>
	<div id="collection-stats" class="box">
		<h3>SKOS Concepts per class:</h3>
		<ul>
			<?php foreach ($this->collection->getClasses() as $class => $count):?>
			<li><?php echo OpenSKOS_Rdf_Parser::$namespaces['skos'].$class?>: <?php echo number_format($count, 0)?></li>
			<?php endforeach?>
		</ul>
	</div>
</div>
<h3>Alternative formats</h3>
<ul>
	<li><a class="json" href="<?php echo str_replace('.html', '.json', $this->url())?>">JSON</a></li>
	<li><a class="jsonp" href="<?php echo str_replace('.html', '.jsonp', $this->url()) . '&callback=myCallback_1234'?>">JSONP</a></li>
	<li><a class="rdf" href="<?php echo str_replace('.html', '.rdf', $this->url())?>">RDF</a></li>
</ul>
