<?php

?>
<?php $this->headTitle($this->translate('Collections')) ?>
<h2><?php echo $this->translate('Collections') ?></h2>
<p>These are the avaliable collections:</p>
<ul>
    <?php foreach ($this->collections as $collection): ?>
        <li>
            <a href="<?php echo $this->url(array('id' => $collection->tenant . ':' . $collection->code), 'rest') ?>.html">
                <strong><?php echo $collection->dc_title ?></strong>
            </a>
        </li>
    <?php endforeach ?>
</ul>
<h3>Alternative formats</h3>
<ul>
    <li><a class="json" href="<?php echo $this->url() ?>?format=json">JSON</a></li>
    <li><a class="jsonp" href="<?php echo $this->url() ?>?format=jsonp&callback=myCallback_1234">JSONP</a></li>
    <li><a class="rdf" href="<?php echo $this->url() ?>">RDF</a></li>
</ul>
