<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Manage jobs'))?>

<p>
<?php if ($this->hideFinishedJobs):?>
<a href="<?php echo $this->url(array('hide-finished-jobs' => null))?>"><?php echo $this->translate('Show finished jobs')?> &raquo;</a>
<?php else:?>
<a href="<?php echo $this->url(array('hide-finished-jobs' => 1))?>"><?php echo $this->translate('Hide finished jobs')?> &raquo;</a>
<?php endif?>
</p>
<?php if (!count($this->jobs)):?>
<p><?php echo $this->translate('There are no jobs scheduled.')?></p>
<?php else:?>
<?php 
$msg_0 = $this->translate('No jobs selected');
$msg_1 = $this->translate('Are you sure you want to delete the selected job?');
$msg_more = $this->translate('Are you sure you want to delete the selected jobs?');
$js = <<<JS
window.addEvent('load', function(){
	new CheckAllBoxes(\$('checkall'), \$\$('.jobCb'));
	\$('jobForm').addEvent('submit', function (ev){
		var s = 0;
		\$\$('.jobCb').each(function(el){
			s+=el.get('checked')?1:0;
		});
		switch (s) {
			case 0:
				alert('{$msg_0}');
				(new Event(ev)).stop();
				break;
			default:
				if (!confirm(s==1?'{$msg_1}':'{$msg_more}')) {
					return false;
				}
				break;
		}
		console.log(s);
	});
});
JS;
$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, $js);
?>
<form method="post" action="<?php echo $this->url(array('action' => 'delete'))?>" id="jobForm">
<table>
	<thead>
		<tr>
			<th><input type="checkbox" id="checkall"/></th>
			<th><?php echo $this->translate('Collection')?></th>
			<th><?php echo $this->translate('Created')?></th>
			<th><?php echo $this->translate('Started')?></th>
			<th><?php echo $this->translate('Finished')?></th>
			<th><?php echo $this->translate('Task')?></th>
			<th><?php echo $this->translate('Status')?></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->jobs as $job):?>
		<tr>
			<td><input type="checkbox" class="jobCb" name="job[]" value="<?php echo $job['id']?>"/></td>
			<td><?php echo $job['collection']?></td>
			<td><?php echo $job['created']?></td>
			<td><?php echo $job['started']?$job['started']:'-'?></td>
			<td><?php echo $job['finished']?$job['finished']:'-'?></td>
			<td><?php echo $job['task']?></td>
			<td class="job-status-<?php echo strtolower($job['status'])?>"><?php echo $job['status']?></td>
			<td>
			<?php if(!$this->started):?>
				<a href="<?php echo $this->url(array('action' => 'view', 'job' => $job['id']))?>"><?php echo $this->translate('details')?>&raquo;</a>
			<?php else:?>
			&nbsp;
			<?php endif?>
			</td>
		</tr>
		<?php endforeach?>
	</tbody>
</table>
<p>
	<input type="submit" value="<?php echo $this->translate('Delete selected jobs')?>"/>
</p>
</form>
<?php endif?>
