<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
use OpenSkos2\Namespaces\OpenSkos;
use OpenSkos2\Namespaces\Skos;
?>

<div id="concept-header">
    <div id="concept-header-items">
        <div class="item">
            <span><?php echo $this->translate('URI:'); ?> </span>
            <?php echo $this->currentConcept->getUri(); ?>
        </div>
        <?php if ($this->tenant->getPropertyFlatValue(OpenSkos::ENABLESTATUSSESSYSTEMS)): ?>
            <div class="item" id="concept-status">
                <span><?php echo $this->translate('Status:'); ?> </span>
                <?php echo ($this->currentConcept->isPropertyEmpty(OpenSkos::STATUS) ? $this->translate('undefined') : $this->translate($this->currentConcept->getPropertyFlatValue(OpenSkos::STATUS))); ?>
            </div>
        <?php endif ?>
        <div class="item" id="concept-checked">
            <span><?php echo $this->translate('To be checked:'); ?> </span>
            <?php echo $this->currentConcept->isPropertyTrue(OpenSkos::TOBECHECKED) ? $this->translate('Yes') : $this->translate('No'); ?>
        </div>
        <div class="item">
            <span><?php echo $this->translate('Notations:'); ?> </span>
            <?php echo $this->currentConcept->getPropertyFlatValue(Skos::NOTATION); ?>
        </div>
    </div>
    <div id="concept-action">
        <input id="uri" type="hidden" value="<?php echo $this->currentConcept->getUri(); ?>" />
        <?php if (OpenSKOS_Db_Table_Users::fromIdentity()->isAllowed('editor.concepts', 'edit')): ?>
            <?php if ($this->currentConcept->getTenant() == OpenSKOS_Db_Table_Users::fromIdentity()->tenant): ?>
                <button id="concept-edit">
                    <?php echo $this->translate('Switch to edit mode'); ?>
                </button>
            <?php else: ?>
                <?php echo $this->translate('Tenant:') . ' "' . $this->currentConcept->getTenant() . '"' ?>
            <?php endif ?>
        <?php endif ?>
        <button class="export-concept export">
            <?php echo $this->translate('Export'); ?>
        </button>
    </div>
    <div class="clear">&nbsp;</div>
</div>