<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
use OpenSkos2\Namespaces\Skos;
use OpenSkos2\Namespaces\SkosXl;

$diContainer = Zend_Controller_Front::getInstance()->getDispatcher()->getContainer();
$labelManager = $diContainer->get('OpenSkos2\SkosXl\LabelManager');
?>

<div id="concept-language-tab-container" class="concept-language-tab-container">
    <div id="concept-view-language-tabs">
        <ul id="tab-links-language">
            <?php $isFirst = true; ?>
            <?php foreach ($this->currentConcept->retrieveLanguages() as $languageCode): ?>
                <li id="tab_<?= $languageCode; ?>" class="concept-tab-link tab<?php if ($isFirst): $isFirst = false ?> active<?php endif ?>">
                    <a href="#" id="language_<?= $languageCode; ?>"><?= strtoupper($languageCode); ?></a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>

    <?php
    // @TODO Merge those lists with the once in the form.
    $labelNames = array(
        Skos::PREFLABEL => _('Preferred label'),
        Skos::ALTLABEL => _('Alternative label'),
        Skos::HIDDENLABEL => _('Hidden label')
    );
    $propertyNames = array(
        Skos::SCOPENOTE => _('Scope Note'),
        Skos::NOTE => _('Note'),
        Skos::EXAMPLE => _('Example'),
        Skos::DEFINITION => _('Definition'),
        Skos::CHANGENOTE => _('Change note'),
        Skos::EDITORIALNOTE => _('Editorial note'),
        Skos::HISTORYNOTE => _('History note')
    );
    $skosXlNames = array(
        SkosXl::PREFLABEL => _('Skos Xl preferred label'),
        SkosXl::ALTLABEL => _('Skos Xl alternative label'),
        SkosXl::HIDDENLABEL => _('Skos Xl hidden label'),
    );
    ?>
    <?php foreach ($this->currentConcept->retrieveLanguages() as $languageCode): ?>
        <div id="tab_language_<?= $languageCode; ?>" class="tab-content">
            <?php if($this->tenant->getEnableSkosXl() === false): ?>
            <div class="concept-left" id="concept-lexical">
                <div class="concept-left-content">
                    <ul id="concept-lexical-list">
                        <?php foreach ($labelNames as $labelKey => $labelTitle): ?>
                            <?php if ($this->currentConcept->hasPropertyInLanguage($labelKey, $languageCode)) : ?>
                                <li>
                                    <div class="concept-lexical-field"><?= $labelTitle; ?></div> 
                                    <div class="concept-lexical-values">
                                        <ul>
                                            <?php foreach ($this->currentConcept->retrievePropertyInLanguage($labelKey, $languageCode) as $label): ?>
                                                <li id="pref_Label"><?= $label; ?></li>
                                            <?php endforeach ?>
                                        </ul>
                                    </div>
                                    <div class="clear"></div>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
            <?php endif; ?>
                       
            <?php if($this->tenant->getEnableSkosXl() === true): ?>
            <div class="concept-left" id="concept-skos-xl-labels">
                <div class="concept-right-content">
                    <ul>
                        <?php foreach ($skosXlNames as $property => $title): ?>
                            <?php
                                // @TODO Optimize - do not load each label separately.
                                // Gets all literal forms in the current language.
                                $literalForms = [];
                                $labelParams = [];
                                foreach ($this->currentConcept->getProperty($property) as $labelUri) {
                                    if ($labelManager->askForUri($labelUri)) {
                                        $label = $labelManager->fetchByUri($labelUri);
                                        $literalForm = $label->getProperty(SkosXl::LITERALFORM)[0];
                                        if ($literalForm->getLanguage() == $languageCode) {
                                            $literalForms[] = $literalForm->getValue();
                                            $labelParams[] = [
                                                'literalForm' => $literalForm->getValue(),
                                                'uri' => $labelUri
                                            ];
                                        }
                                    }
                                }
                            ?>
                        
                            <?php if (!empty($labelParams)) : ?>
                                <li>
                                    <div class="concept-lexical-field"><?= $title; ?></div> 
                                    <div class="concept-lexical-values">
                                        <ul>
                                            <?php foreach ($labelParams as $labelParam): ?>
                                                <li title="<?= $labelParam['uri']; ?>"><?= $labelParam['literalForm']; ?>
                                                <a class="skos-xl-label-show-more"
                                                   data-label-uri="<?= $labelParam['uri'] ?>"
                                                   href="<?= $this->url([
                                                        'module' => 'editor', 
                                                        'controller' => 'label',  
                                                        'action' => 
                                                        'view'], null, true)?>"></a>
                                                </li>
                                            <?php endforeach ?>
                                        </ul>
                                    </div>
                                    <div class="clear"></div>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
            <?php endif; ?>
            
            <div class="concept-left" id="concept-document">
                <div class="concept-right-content">
                    <ul id="concept-document-list">
                        <?php foreach ($propertyNames as $docKey => $docTitle): ?>
                            <?php if ($this->currentConcept->hasPropertyInLanguage($docKey, $languageCode)) : ?>
                                <li>
                                    <div class="concept-document-field"><?= $docTitle; ?></div> 
                                    <div class="concept-document-values">
                                        <ul>
                                            <?php foreach ($this->currentConcept->retrievePropertyInLanguage($docKey, $languageCode) as $docValue): ?>
                                                <li id="pref_Label"><?= $docValue; ?></li>
                                            <?php endforeach ?>
                                        </ul>
                                    </div>
                                    <div class="clear"></div>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>