<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Boyan Bonev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
use OpenSkos2\Namespaces\Skos;
?>

<div id="concept-language-tab-container" class="concept-language-tab-container">
    <div id="concept-view-language-tabs">
        <ul id="tab-links-language">
            <?php $isFirst = true; ?>
            <?php foreach ($this->currentConcept->retrieveLanguages() as $languageCode): ?>
                <li id="tab_<?php echo $languageCode; ?>" class="concept-tab-link tab<?php if ($isFirst): $isFirst = false ?> active<?php endif ?>">
                    <a href="#" id="language_<?php echo $languageCode; ?>"><?php echo strtoupper($languageCode); ?></a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>

    <?php
    $labelNames = array(
        Skos::PREFLABEL => _('Preferred label'),
        Skos::ALTLABEL => _('Alternative label'),
        Skos::HIDDENLABEL => _('Hidden label')
    );
    $propertyNames = array(
        Skos::SCOPENOTE => _('Scope Note'),
        Skos::NOTE => _('Note'),
        Skos::EXAMPLE => _('Example'),
        Skos::DEFINITION => _('Definition'),
        Skos::CHANGENOTE => _('Change note'),
        Skos::EDITORIALNOTE => _('Editorial note'),
        Skos::HISTORYNOTE => _('History note')
    );
    ?>
    <?php foreach ($this->currentConcept->retrieveLanguages() as $languageCode): ?>
        <div id="tab_language_<?php echo $languageCode; ?>" class="tab-content">
            <div class="concept-left" id="concept-lexical">
                <div class="concept-left-content">
                    <ul id="concept-lexical-list">
                        <?php foreach ($labelNames as $labelKey => $labelTitle): ?>
                            <?php if ($this->currentConcept->hasPropertyInLanguage($labelKey, $languageCode)) : ?>
                                <li>
                                    <div class="concept-lexical-field"><?php echo $labelTitle; ?></div> 
                                    <div class="concept-lexical-values">
                                        <ul>
                                            <?php foreach ($this->currentConcept->retrievePropertyInLanguage($labelKey, $languageCode) as $label): ?>
                                                <li id="pref_Label"><?php echo $label; ?></li>
                                            <?php endforeach ?>
                                        </ul>
                                    </div>
                                    <div class="clear"></div>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>

            <div class="concept-left" id="concept-document">
                <div class="concept-right-content">
                    <ul id="concept-document-list">
                        <?php foreach ($propertyNames as $docKey => $docTitle): ?>
                            <?php if ($this->currentConcept->hasPropertyInLanguage($docKey, $languageCode)) : ?>
                                <li>
                                    <div class="concept-document-field"><?php echo $docTitle; ?></div> 
                                    <div class="concept-document-values">
                                        <ul>
                                            <?php foreach ($this->currentConcept->retrievePropertyInLanguage($docKey, $languageCode) as $docValue): ?>
                                                <li id="pref_Label"><?php echo $docValue; ?></li>
                                            <?php endforeach ?>
                                        </ul>
                                    </div>
                                    <div class="clear"></div>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>