<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
use OpenSkos2\Namespaces\Skos;
?>

<div class="concept-scheme-relation-grid <?= $this->key ?>">
    <div class="concept-item-subtitle">
        <?= $this->title; ?>
        <span class="relations-count">( <?= count($this->relations); ?> )</span>
    </div>
    <ul class="concept-relation-list">
        <?php foreach ($this->relations as $key => $concept): ?>
            <li class="concept-link">
                <span class="concept-link-header"> 
                    <?= $this->partial(
                        'concept/view/schemes.phtml',
                        [
                            'concept' => $concept,
                            'conceptSchemes' => $this->conceptSchemes,
                        ]
                    );?>
                </span>
                
                <span class="concept-link-content">
                    <?php
                        $language = Zend_Registry::get('Zend_Locale')->getLanguage();
                        $scopeNote = $concept->getPropertyFlatValue(Skos::SCOPENOTE, $language);
                    ?>
                    <a href="#" title="<?= $concept->getCaption($language); ?>
                        <?= (empty($scopeNote) ? '' : ' {' . $scopeNote . '}') ?>">
                        <?= $concept->getCaption($language); ?>
                        <?php // if (!$this->currentConcept->isInternalRelation($concept['uri'], $relation)) : ?>
                            <!--*-->
                        <?php // endif ?>
                    </a>
                </span>
                <span class="uri"><?= $concept->getUri(); ?></span>
            </li>
        <?php endforeach ?>
    </ul>
</div>