<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Boyan Bonev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
use OpenSkos2\Namespaces\Skos;
?>

<div class="concept-scheme-relation-grid <?= $this->key ?>">
    <div class="concept-item-subtitle">
        <?= $this->title; ?>
        <span class="relations-count">( <?= count($this->relations); ?> )</span>
    </div>
    <ul class="concept-relation-list">
        <?php foreach ($this->relations as $key => $concept): ?>
            <li class="concept-link">
                <span class="concept-link-header"> 
                    <?php if (!$concept->isPropertyEmpty(Skos::INSCHEME)): ?>
                        <?php foreach ($concept->getProperty(Skos::INSCHEME) as $schemeUri) : ?>
                            <?php
                                $scheme = $this->conceptSchemes->findByUri($schemeUri);
                                if (!empty($scheme)) {
                                    $imgTitle = $scheme->getPreviewTitle();
                                    $iconPath = OpenSkos2\ConceptScheme::buildIconPath($scheme->getUri());
                                }
                            ?>
                            <?php if (!empty($iconPath)): ?>
                                <img alt="<?= $imgTitle ?>" title="<?= $imgTitle ?>" src="<?= $iconPath ?>" />
                            <?php else: ?>
                                <span>(<?= empty($imgTitle) ? 'N/A' : substr($imgTitle, 0, 2) ?>)</span>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </span>
                
                <span class="concept-link-content">
                    <?php
                        $scopeNote = $concept->retrievePropertyInLanguage(
                            Skos::SCOPENOTE,
                            Zend_Registry::get('Zend_Locale')->getLanguage()
                        );
                    ?>
                    <a href="#" title="<?= $concept->getPreviewTitle(); ?>
                        <?= (empty($scopeNote) ? '' : ' {' . $scopeNote . '}') ?>">
                        <?= $concept->getPreviewTitle(); ?>
                        <?php // if (!$this->currentConcept->isInternalRelation($concept['uri'], $relation)) : ?>
                            <!--*-->
                        <?php // endif ?>
                    </a>
                </span>
                <span class="uri"><?= $concept->getUri(); ?></span>
            </li>
        <?php endforeach ?>
    </ul>
</div>