<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
use OpenSkos2\Namespaces\Skos;

$diContainer = Zend_Controller_Front::getInstance()->getDispatcher()->getContainer();
$conceptSchemes = $diContainer->get('Editor_Models_ConceptSchemesCache')->fetchAll();
?>

<?php if (!$this->concept->isPropertyEmpty(Skos::INSCHEME)): ?>
    <?php foreach ($this->concept->getProperty(Skos::INSCHEME) as $schemeUri) : ?>
        <?php
            $scheme = $conceptSchemes->findByUri($schemeUri);
            if (!empty($scheme)) {
                $imgTitle = $scheme->getCaption();
                $iconPath = $scheme->getIconPath();
            }
        ?>
        <?php if (!empty($iconPath)): ?>
            <img alt="<?= $imgTitle ?>" title="<?= $imgTitle ?>" src="<?= $iconPath ?>" />
        <?php else: ?>
            <span>(<?= empty($imgTitle) ? 'N/A' : substr($imgTitle, 0, 2) ?>)</span>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>