<?php if ($this->user->id):?>
<?php $this->headTitle ($this->translate('Edit user'))?>
<?php echo $this->render('menu.phtml');?>
<h2><?php echo $this->translate('Edit user')?></h2>
<?php else:?>
<?php $this->headTitle ($this->translate('Create user'))?>
<?php echo $this->render('menu.phtml');?>
<h2><?php echo $this->translate('Create user')?></h2>
<?php endif?>

<?php echo $this->user->getForm()->setAction($this->url(array('action' => 'save')))?>

<?php 
//code to inject a random API key
$serverUrl = $this->serverUrl();
$js = <<<JS
function randomString(string_length) {
	var chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";
	var randomstring = '';
	for (var i=0; i<string_length; i++) {
		var rnum = Math.floor(Math.random() * chars.length);
		randomstring += chars.substring(rnum,rnum+1);
	}
	return randomstring;
}

window.addEvent('load', function(){
	Asset.image('{$serverUrl}/assets/images/keygen.png', {
	    title: 'Generate random API key',
	    styles: {'margin-left': 10, 'cursor' : 'pointer'},
	    events: {
	    	click: function() {
	    		\$('apikey').set('value', randomString(16));
	    	}
	    },
	    onLoad: function() {
	    	this.inject(\$('apikey'), 'after');
	    }
	});
	
	
});
JS;
$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, $js);
?>