<?php

/*
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */

/* @var $concept \OpenSkos2\Concept */
$concept = $this->concept;

$lang = Zend_Controller_Front::getInstance()->getRequest()->getParam('lang');
$title = $concept->getCaption($lang);
$this->headTitle($title);
?>
<h2><?=$this->escape($title)?></h2>
<dl>
    <dt><?=$this->translate('Institution')?>:</dt>
    <dd><a href="<?=$this->url([
                'module' => 'api',
                'controller' => 'institutions',
                'id' => (string)$concept->getTenant()
            ],
            'rest'
        )?>.html"><?=$this->escape($concept->getInstitution()->name)?></a></dd>
    <?php /* @todo Fix skos:Collection to openskos:Collection first before add this
    <dt><?=$this->translate('Collection')?>:</dt>
    <dd>
        <a href="<?=$this->url(array(
                                    'module' => 'api',
                                    'controller' => 'collections',
                                    'id' => $collection->getId()
                                ), 'rest'
                )?>.html"><?=$collection->dc_title?></a>
    </dd>
     */
    ?>
    <dt>URI:</dt>
    <dd>
        <a rel="external" href="<?=$this->escape($concept->getUri())?>"><?=$this->escape($concept->getUri())?></a>
    </dd>
    <dt>SKOS Class:</dt>
    <dd><a rel="external" href="<?=$concept::TYPE?>"><?=$concept::TYPE?></a></dd>
</dl>

<?php if ($inScheme = $concept->getProperty(\OpenSkos2\Namespaces\Skos::INSCHEME)):?>
    <h3><?=$this->translate('inScheme')?></h3>
    <ul>
        <?php foreach ($inScheme as $uri):?>
            <li><a href="<?php echo $this->url([
                        'module' => 'api',
                        'controller' => 'redirect',
                        'action' => 'index',
                        'id' => null
                    ], 'default'
                    )?>?id=<?=$this->escape($uri)?>&format=html"><?=$this->escape($uri)?></a></li>
        <?php endforeach?>
    </ul>
<?php endif?>

<?php foreach (\OpenSkos2\Concept::$classes as $className => $fieldsInClass):?>
    <h3><?=$this->translate($className)?></h3>
    <?php foreach ($fieldsInClass as $subClass):?>

        <?php
        $values = $concept->getProperty($subClass);
        if (!count($values)) {
            continue;
        }
        ?>

        <h4><?=$this->translate('skos:'.$subClass)?></h4>

        <ul class="<?php echo $subClass?>">
            <?php foreach ($values as $value):?>
                <li>
                    <a class="resolvable-concept"
                       href="<?=$this->url(['module' => 'api', 'controller' => 'concept', 'id' => null], 'rest')?>?id=<?=$value?>&format=html">
                        <?php if (method_exists($value, 'getLanguage') && $value->getLanguage()): ?>
                            <span class="label" xml:lang="<?=$value->getLanguage()?>"><?=$this->escape($value)?></span>
                            <span class="lang <?=$lang?>">(<?=$lang?>)</span>
                        <?php else:?>
                            <?=$this->escape($value)?>
                        <?php endif?>
                    </a>
                </li>
            <?php endforeach?>
        </ul>
    <?php endforeach; ?>
<?php endforeach; ?>

<h3><?=$this->translate('Alternative formats')?></h3>
<ul>
    <li><a class="rdf" href="<?=$this->url(['id' => $concept->getUuid()])?>.rdf">RDF</a></li>
    <li><a class="json" href="<?=$this->url(['id' => $concept->getUuid()])?>.json">JSON</a></li>
    <li><a class="jsonp" href="<?=$this->url(['id' => $concept->getUuid()])?>.jsonp?callback=callback">JSONP</a></li>
</ul>