<?php
/* 
 * OpenSKOS
 * 
 * LICENSE
 * 
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * 
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php
$exampleResolveURI = 'http://hdl.handle.net/11148/CCR_C-4430_ee9b9819-8c50-2962-29d7-84a450bd0af2';
$exampleResolveUUID = 'CCR_C-4430_ee9b9819-8c50-2962-29d7-84a450bd0af2';
$exampleResolveLabel = 'testing';
?>
<h2><?php echo $this->escape('OpenSKOS Concept resolver') ?></h2>
<p>Use this API to resolve a concept.</p>
<h3 id="concept-resolver">Concept resolver</h3>
<ul>
    <li>
        <p>Resolve the concept "<em><?php echo $exampleResolveLabel ?></em>" by it's UUID</p>
        <ul>
            <li>
                in RDF: <a href="<?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.rdf"><?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.rdf</a>
            </li>
            <li>
                in HTML: <a href="<?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.html"><?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.html</a>
            </li>
            <li>
                in JSON: <a href="<?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.json"><?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.json</a>
            </li>
            <li>
                in JSONP: <a href="<?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.jsonp?callback=myCallback_1234"><?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.jsonp?callback=myCallback_1234</a>
            </li>
            <li>
                in XML: <a href="<?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.xml"><?php echo $this->url(array('controller' => 'concept', 'id' => $exampleResolveUUID)) ?>.xml</a>
            </li>
        </ul>
        <p>Resolve the concept "<em><?php echo $exampleResolveLabel ?></em>" by it's URI</p>
        <ul>
            <li>
                in RDF: <a href="<?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&format=rdf"><?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&amp;format=rdf</a>
            </li>
            <li>
                in HTML: <a href="<?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>"><?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?></a>
            </li>
            <li>
                in JSON: <a href="<?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&format=json"><?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&amp;format=json</a>
            </li>
            <li>
                in JSONP: <a href="<?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&format=jsonp&callback=myCallback_1234"><?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&amp;format=jsonp&amp;callback=myCallback_1234</a>
            </li>
            <li>
                in XML: <a href="<?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&format=xml"><?php echo $this->url(array('controller' => 'concept')) ?>?id=<?php echo $exampleResolveURI ?>&amp;format=xml</a>
            </li>
        </ul>
    </li>
</ul>

