<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Manage institution'))?>

<div>
	<div id="collection-form">
		<?php echo $this->tenant->getForm()?>
        <div class="decorator-helptext" id="decorator-helptext-statuses">
            <div class="help-text-title">Enable the statuses system for concepts:</div>
            <div class="help-text-content">
                <ul>
                    <li>This allows having "candidate", "approved", "obsolete" and other concepts.</li>
                    <li>Checking/unchecking the checkbox will not update any statuses of concepts.</li>
                    <li>When <strong>unchecked</strong> all edited and created concepts get the status approved. All searches search for any status.</li>
                    <li>When <strong>checked</strong> all options for statuses (in search and create/edit) will appear.</li>
                    <li>Status "DELETED" and deleted concepts are not affected from this option.</li>
                </ul>
            </div>
        </div>
        <div class="decorator-helptext" id="decorator-helptext-skosxl">
            <div class="help-text-title">Checking this option will allow you to use SKOS-XL labels instead of simple value labels:</div>
            <div class="help-text-content">
                <ul>
                    <li>If this option is enabled SKOS-XL labels will replace the current simple labels -
                        Only SKOS-XL labels will be available in the editor. Current values will be preserved.</li>
                    <li>You will be able to revert to the old simple value labels any time later on.</li>
                    <li>SKOS-XL labels can be used as Preferred, Alternative and Hidden labels.</li>
                </ul>
            </div>
        </div>
	</div>
	<div id="collection-stats" class="box">
		<p><?php echo $this->translate('You can share this information via the OpenSKOS API')?>:</p>
		<ul>
			<li><a href="<?php echo $this->url(array('module' => 'api', 'controller'=>'institutions', 'id' => $this->tenant->code), 'rest', true)?>.rdf">in RDF (VCard)</a></li>
			<li><a href="<?php echo $this->url(array('module' => 'api', 'controller'=>'institutions', 'id' => $this->tenant->code), 'rest', true)?>.html">in HTML</a></li>
			<li><a href="<?php echo $this->url(array('module' => 'api', 'controller'=>'institutions', 'id' => $this->tenant->code), 'rest', true)?>.json">in JSON</a></li>
		</ul>
	</div>
</div>
	