<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Alexandar Mitsev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>

<div id="concept-scheme-edit-form">
	<h2><?php echo $this->translate('Create concept scheme')?></h2>
	
	<?php if ( ! empty($this->errors)) :?>
		<div class="errors">
			<?php if (in_array('isEmpty', $this->errors['uriBase'])) :?>
				<div><?php echo $this->translate('The base part of the "Uri" is required.')?></div>
			<?php endif?>
			<?php if (in_array('isEmpty', $this->errors['uriCode'])) :?>
				<div><?php echo $this->translate('The last part of the "Uri" is required.')?></div>
			<?php endif?>
			<?php if (in_array('isEmpty', $this->errors['dcterms_title'])) :?>
				<div><?php echo $this->translate('The "Title" is required and must be filled in each language.')?></div>
			<?php endif?>
		</div>
	<?php endif ?>
	
	<?php echo $this->form;?>
</div>