<?php
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Alexndar Mitsev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */

use OpenSkos2\Namespaces\OpenSkos;

?>
<?php $this->headTitle($this->translate('Manage concept schemes')) ?>

<p><a href="<?= $this->url(array('action' => 'index', 'controller' => 'index')) . '#addConceptScheme/1/' ?>"><?= $this->translate('Create new concept scheme') ?> &raquo;</a></p>
<p><a href="<?= $this->url(array('action' => 'show-icons')) ?>"><?= $this->translate('Manage icons') ?> &raquo;</a></p>
<?php if (!count($this->conceptSchemes)): ?>
    <div class="note">
        <p><?= $this->translate('No schemes.') ?></p>
    </div>
<?php else: ?>
    <table id="concept-schemes-list">
        <thead>
            <tr>
                <th>#</th>
                <th><?= $this->translate('Scheme') ?></th>
                <th><?= $this->translate('Collection') ?></th>
                <th><?= $this->translate('Icon') ?></th>
                <th><?= $this->translate('Delete') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->conceptSchemes as $i => $conceptScheme): ?>
                <tr class="<?= $i % 2 ? 'even' : 'uneven' ?>">
                    <th scope="row"><?= $i + 1 ?></th>
                    <td>
                        <?= $conceptScheme->getCaption();?>
                    </td>
                    <td>
                        <?= $set = $conceptScheme->getPropertySingleValue(OpenSkos::SET)?>
                        <?= (isset($this->collectionsMap[$set]) ? $this->collectionsMap[$conceptScheme[$set]] : '') ?>
                    </td>
                    <td>
                        <a id="<?= $conceptScheme->getUri() ?>" class="assign-icon" href="#" title="<?= $this->translate('Change Icon') ?>">
                            <?php $iconPath = $conceptScheme->getIconPath();?>
                            <?php if (!empty($iconPath)): ?>
                                <img src="<?= $iconPath ?>" />
                            <?php else: ?>
                                <span><?= $this->translate('no icon') ?></span>
                            <?php endif ?>
                        </a>
                    </td>
                    <td>
                        <?php if (isset($this->conceptSchemesWithDeleteJobs[$conceptScheme->getUri()])): ?>
                            <a href="<?= $this->url(array('controller' => 'jobs', 'action' => 'view', 'job' => $this->conceptSchemesWithDeleteJobs[$conceptScheme->getUri()])) ?>" title="<?= $this->translate('Go to the delete job details') ?>"><?= $this->translate('A delete job exists') ?></a>
                        <?php else: ?>
                            <a class="delete" href="<?= $this->url(array('action' => 'delete', 'uri' => $conceptScheme->getUri())) ?>" title="<?= $this->translate('Delete') ?>"><?= $this->translate('Delete concept scheme') ?></a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>

<?php
$confirmationMessage = $this->translate('Are you sure you want to delete the concept scheme?');
$js = <<<JS
window.addEvent('load', function() {
	$$('.delete').each(function (el) {
		el.addEvent('click', function (e) {
			e.preventDefault();
			if (confirm('{$confirmationMessage}')) {
				window.location.href = new Element(e.target).get('href');
			}
		});
	});
});
JS;
$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, $js);
?>

<div id="assign-icons-box" class="assign-icons-box do-not-show">
    <input type="hidden" class="schemeUuid" />
    <?php foreach ($this->uploadedIcons as $icon) : ?>
        <img class="<?= $icon['iconFile'] ?>" src="<?= $icon['httpPath'] ?>" title="<?= $icon['iconFile'] ?>" />
    <?php endforeach ?>
</div>

<?php
$baseUrl = $this->url(array(), 'default', true);
if ($baseUrl)
    $baseUrl = rtrim($baseUrl, '/') . '/';
$this->headScript(Zend_View_Helper_HeadScript::FILE, $baseUrl . 'assets/scripts/editor/conceptSchemesIcons.js');
?>