<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Alexndar Mitsev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Manage icons'))?>

<div id="manage-icons-list" class="manage-icons-list">
	<?php foreach ($this->uploadedIcons as $icon) :?>
		<img id="<?php echo $icon['iconFile']?>" src="<?php echo $icon['httpPath']?>" title="<?php echo $this->translate('Delete')?>" />
	<?php endforeach?>
</div>

<div id="delete-confirmation-message" class="do-not-show">
	<?php echo $this->translate('Are you sure you want to delete this icon?')?>
</div>

<?php echo $this->uploadIconForm;?>

<?php
	$baseUrl = $this->url(array(), 'default', true);
	if ($baseUrl) $baseUrl = rtrim($baseUrl, '/').'/';
	$this->headScript(Zend_View_Helper_HeadScript::FILE, $baseUrl . 'assets/scripts/editor/conceptSchemesIcons.js');
?>