<?php
$this->headTitle ( 'Welkom to OpenSKOS' );
?>
<h2>Welcome to OpenSKOS</h2>
<ul>
	<li><a href="#what-is-OpenSKOS">What is OpenSKOS?</a></li>
	<li><a href="#dashboard">Dashboard</a></li>
	<li><a href="#api">API</a></li>
	<li><a href="#api">OAI-PMH</a></li>
</ul>

<h3 id="what-is-OpenSKOS">What is OpenSKOS?</h3>
<p>OpenSKOS is a <a rel="external" href="http://www.catchplus.nl/">CATCHPlus</a> project. It provides API's on <a href="http://www.w3.org/2004/02/skos/" rel="external">SKOS (Simple Knowledge Organization System)</a>. 
You can either join OpenSKOS as a "tenant" in a SaaS (Software as a Service) construction, or you can download the source code and run your own instance of thios software.</p>
<p>[<a href="#top">top</a>]</p>

<h3 id="dashboard">Dashboard</h3>
<p>The OpenSKOS software has a dasboard in wich you can manage tour own SKOS structures.</p>
<p>If you are a "tenant" of this instance of the OpenSKOS you can <a href="<?php echo $this->url(array('module' => 'dashboard'))?>">login</a> with your credentials.</p>
<p>[<a href="#top">top</a>]</p>

<h3 id="api">API</h3>
<p>Visit the <a
	href="<?php
	echo $this->url ( array ('controller' => 'api' ) )?>">OpenSKOS
API section &raquo;</a></p>
<p>[<a href="#top">top</a>]</p>

<h3 id="oai-pmh">OAI-PMH</h3>
<p>The <a rel="external" href="http://www.openarchives.org/pmh/">Open Archives Initiative Protocol for Metadata Harvesting</a>
(OAI-PMH) is a low-barrier mechanism for repository interoperability.
Data Providers are repositories that expose structured metadata via
OAI-PMH. Service Providers then make OAI-PMH service requests to harvest
that metadata. OAI-PMH is a set of six verbs or services that are
invoked within HTTP. The OpenSKOS project supports 2 <a rel="external" href="http://www.openarchives.org/OAI/openarchivesprotocol.html#MetadataNamespaces">metadataPrefixes</a>: <em>oai_dc</em> and <em>oai_rdf</em>.</p>
<p>OpenSKOS implements a Service Provider:</p>
<ul>
	<li>Identify:<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=Identify"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=Identify</a>
	</li>
	<li>List metadataPrefixes:<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListMetadataFormats"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListMetadataFormats</a>
	</li>
	<li>List ConceptSchemes (as OAI-PMH "sets"):<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListSets"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListSets</a>
	</li>
	<li>List Concepts:<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&metadataPrefix=oai_dc"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&amp;metadataPrefix=oai_dc</a>
	</li>
	<li>List Concepts modified since <em>2011-09-01 12:00:00</em>:<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&metadataPrefix=oai_dc&from=2011-09-01T12:00:00Z"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&amp;metadataPrefix=oai_dc&amp;from=2011-09-01T12:00:00Z</a>
	</li>
	<li>List Concepts modified between <em>2011-09-01</em> and <em>2011-09-10</em>:<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&metadataPrefix=oai_dc&from=2011-09-01&until=2011-09-10"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&amp;metadataPrefix=oai_dc&amp;from=2011-09-01&amp;until=2011-09-10</a>
	</li>
	<li>List Concepts in ConceptScheme "<em>GeografischeNamen</em>" (uuid 3fe93807-8ad0-2828-ffb2-6b1226846f05):<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&metadataPrefix=oai_dc&set=3fe93807-8ad0-2828-ffb2-6b1226846f05"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=ListRecords&amp;metadataPrefix=oai_dc&amp;set=3fe93807-8ad0-2828-ffb2-6b1226846f05</a>
	</li>
	<li>Get Concepts "<em>A.G. Wildervankkanaal</em>" (uuid 238c8bfb-8915-0379-b52e-0885bfc9e500):<br/>
		<a href="<?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=GetRecord&metadataPrefix=oai_dc&identifier=238c8bfb-8915-0379-b52e-0885bfc9e500"><?php echo $this->url(array('controller' => 'oai-pmh'))?>?verb=GetRecord&amp;metadataPrefix=oai_dc&amp;identifier=238c8bfb-8915-0379-b52e-0885bfc9e500</a>
	</li>
	
</ul>
<p>[<a href="#top">top</a>]</p>
