<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Add openskos xl label to concept'))?>
<div>
    <a class="button" href="<?= $this->url(['controller' => 'label', 'action' => 'choose'])?>">
        <?= $this->translate('Choose existing')?>
    </a>
    <a class="button" href="<?= $this->url(['controller' => 'label', 'action' => 'create'])?>">
        <?= $this->translate('Create new')?>
    </a>
</div>