<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */

?>
<?php $this->headTitle($this->translate('Choose label'))?>
<div class="choose-skos-xl-labels">
    <form id="skosXlLabelsAutocompleteForm" class="autocomplete-form" method="get" action="<?= $this->url(['module' => 'editor', 'controller' => 'label', 'action' => 'autocomplete'], null, true)?>">
        <input class="language" name="language" type="hidden" value="<?= $this->language?>" />
        <input class="autocomplete" name="query" type="text" value="" />
    </form>
    <ul id="skosXlLabelsAutocompleteList" class="list">
        <li class="item template">
            <a class="link" href="#">
                <span class="literalForm"></span>
            </a>
        </li>
    </ul>
</div>

<script>
    window.parent.Editor.Label.initAutocomplete(
        $('skosXlLabelsAutocompleteForm'),
        $('skosXlLabelsAutocompleteList')
    );
</script>