<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Create a new skos xl label'))?>
<div id="label-edit-form">
    <?= $this->form;?>
    <a href="<?= $this->url(['module' => 'editor', 'controller' => 'label', 'action' => 'add-to-concept'], null, true)?>?language=<?= $this->language?>" class="button">
        <?= $this->translate('Back')?>
    </a>
</div>