<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Picturae (http://www.picturae.com)
 * @author     Picturae
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle ($this->translate('Create a concept'))?>
<div id="concept-edit-form">
<h2><?php echo $this->translate('Create concept')?></h2>
<?php echo $this->form;?>
</div>
<span id="doc-properties-not-saved-confirmation" class="do-not-show"><?php echo $this->translate('A document property is not saved. Do you want to continue?')?></span>

<?= $this->render('concept/partials/status-interaction.phtml') ?>