<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Boyan Bonev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle ($this->translate('Edit concept'))?>
<div id="concept-edit-form">
	<h2><?php echo $this->translate('Edit concept')?></h2>

	<?php if ( ! empty($this->errors)) :?>
		<div class="errors">
			<?php foreach ($this->errors as $error) : ?>
				<div>
					<?php echo $error->getMessage();?><br />
					<?php if (count($error->getConflictedConcepts()) > 0) :?>
						<ul>
							<?php foreach ($error->getConflictedConcepts() as $concept) : ?>
								<li class="concept-link">
									<span class="concept-link-content">
										<a class="<?php echo $concept['uuid'];?>" href="#"><?php echo $concept->getMlField('prefLabel', Zend_Registry::get('Zend_Locale')->getLanguage());?></a>
									</span>	
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
		</div>
	<?php endif ?>

	<?php echo $this->form;?>

	<div class="clear">&nbsp;</div>
	<div id="concept-footer">
		<div id="created" class="section">
			<?php echo $this->translate('Created')?><br />
			<?php echo $this->footerData['created']['date']?><br />
			<?php echo $this->footerData['created']['user']?>
		</div>
		<div id="modified" class="section">
			<?php echo $this->translate('Modified')?><br />
			<?php echo $this->footerData['modified']['date']?><br />
			<?php echo $this->footerData['modified']['user']?>
		</div>
		<div id="approved" class="section">
			<?php echo $this->translate('Approved')?><br />
			<?php echo $this->footerData['approved']['date']?><br />
			<?php echo $this->footerData['approved']['user']?>
		</div>
	</div>
</div>
<span id="switch-to-view-confirmation" class="do-not-show"><?php echo $this->translate('Any changes you made will not be saved. Are you sure you want to go back to view mode?')?></span>
<span id="doc-properties-not-saved-confirmation" class="do-not-show"><?php echo $this->translate('A document property is not saved. Do you want to continue?')?></span>
<span id="concept-deleted-successfully" class="do-not-show"><?php echo $this->translate('The concept was successfully deleted.')?></span>

<div id="status-other-concept" class="do-not-show">
    <div class="choose-message redirected"><?= $this->translate('Choose the concept to which this one is redirected.')?></div>
    <div class="choose-message obsolete"><?= $this->translate('Choose the concept which replaces this one.')?></div>
    <div class="hint"><?= $this->translate('Click on a concept in the left search or in right history/selection tabs to choose it.')?></div>
    
    <div class="chosen-concept do-not-show">
        <?= $this->translate('Chosen concept')?>: <span class="chosen-concept-label"></span>
    </div>
    
    <button class="choose-cancel" type="button"><?= $this->translate('Cancel')?></button>
    <button class="choose-ok" type="button"><?= $this->translate('Ok')?></button>
</div>