<?php

/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Boyan Bonev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */

?>

<?php if (isset($this->currentConcept)): ?>
    <div id="concept-view">
        <h2>
            <?php echo $this->currentConcept->getPreviewTitle(); ?>
        </h2>
        <?= $this->render('concept/view/header.phtml') ?>
        <div class="wrapper">
            <div id="concept-content-left">
                <?= $this->render('concept/view/left.phtml') ?>
            </div>
            
            <div id="concept-content-right">
                <?= $this->render('concept/view/right.phtml') ?>
            </div>
        </div>
        <div class="clear">&nbsp;</div>
        <?= $this->render('concept/view/footer.phtml') ?>
    </div>
<?php else: ?>
    <div class="error">
        <p><?php echo $this->errorMessage ?></p>
    </div>
<?php endif?>