<span class="multi-field <?= $this->inputClasses; ?>">
	<label class="concept-multi-label"><?= $this->inputLabel; ?></label>
	<span class="concept-multi-template template">
	<input type="text" name="<?= $this->inputName; ?>[][]" value="" class="concept-multi-input"/>
		<span class="concept-multi-remove"></span>
		<span class="concept-multi-add"></span>
	</span>
<?php if (is_array($this->inputValues)):?>
<?php foreach ($this->inputValues as $value): ?>
	<?php if (isset($value['languageCode'])):  ?>
		<?php if (isset($value['value']) && is_array($value['value'])) :?>
			<?php foreach ($value['value'] as $inputValue): ?>
			<span class="concept-multi-template <?= $value['languageCode']; ?>">
				<input type="text" name="<?= $this->inputName; ?>[<?= $value['languageCode']; ?>][]" value="<?= $this->escape($inputValue); ?>" class="concept-multi-input"/>
				<span class="concept-multi-remove"></span>
				<span class="concept-multi-add"></span>
			</span>
			<?php endforeach?>
		<?php else : ?>
		<input type="text" name="<?= $this->inputName; ?>[<?= $value['languageCode']; ?>][]" value="<?= $this->escape($value['value']); ?>" class="concept-multi-input"/>
		<?php endif?>	
	<?php else: ?>
	<input type="text" name="<?= $this->inputName; ?>[]" value="<?= $this->escape($value); ?>" class="concept-multi-input"/>
	<?php endif?>
<?php endforeach ?>
<?php else:?>
	<input type="text" name="<?= $this->inputName; ?>[]" value="" class="concept-multi-input"/>
		<span class="concept-multi-remove"></span>
	<span class="concept-multi-add"></span>
<?php endif?>
</span>