<div class="multi-field-skos-xl-label <?= $this->inputClasses; ?>">
    <label class="concept-multi-label"><?= $this->inputLabel; ?></label>    
    <a class="skos-xl-label-add" href="<?= $this->url(['controller' => 'label', 'action' => 'add-to-concept'])?>"></a>
    <div class="skos-xl-label template">
        <input type="hidden" name="<?= $this->inputName; ?>[]" value="" class="uri"/>
        <span class="literalForm"></span>
        <span class="skos-xl-label-edit" href="<?= $this->url(['controller' => 'label', 'action' => 'edit'])?>"></span>
        <span class="skos-xl-label-remove"></span>
    </div>
    <?php if (!empty($this->inputValues)):?>
        <?php foreach ($this->inputValues as $labelUris): ?>
            <?php var_dump($labelUris)?>
        <?php endforeach ?>
    <?php endif?>
</div>
