<span class="multi-field-complex" id="<?= $this->inputName; ?>">
    <?php if (is_array($this->inputValues) && !empty($this->inputValues)): ?>
        <?php foreach ($this->inputValues as $schemeUri => $concepts): ?>
            <div class="concept-complex-title <?= $this->inputName; ?>">
                <?= $this->inputLabel; ?> 
                <span class="relations-count">( <?= count($concepts); ?> )</span>
            </div>
            <ul class="multi-field-list <?= $schemeUri ?>">
                <li class="concept-link template">
                    <span class="concept-link-header"></span>
                    <span class="concept-link-content"><a href="#"></a></span>
                    <span class="concept-link-remove-action"><input type="hidden" name="<?= $this->inputName; ?>[]" value="" /></span>
                    <span class="uri"></span>
                </li>
                <?php foreach ($concepts as $concept) : ?>
                    <li class="concept-link">
                        <span class="concept-link-header"> 
                            <?= $this->partial(
                                'concept/view/schemes.phtml',
                                [
                                    'concept' => $concept,
                                    'conceptSchemes' => $this->conceptSchemes,
                                ]
                            );?>
                        </span>
                        
                        <span class="concept-link-content">
                            <?php
                                $language = Zend_Registry::get('Zend_Locale')->getLanguage();
                            ?>
                            <a href="#"><?= $concept->getCaption($language); ?> </a>
                        </span>
                        
                        <span class="concept-link-remove-action">
                            <input type="hidden" name="<?= $this->inputName; ?>[]" value="<?= $concept->getUri(); ?>" />
                        </span>
                        
                        <span class="uri"><?= $concept->getUri(); ?></span>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endforeach ?>
    <?php else: ?>
        <div class="concept-complex-title <?= $this->inputName; ?>">
            <?= $this->inputLabel; ?> 
            <span class="relations-count">( 0 )</span>
        </div>
        <ul class="multi-field-list template">
            <li class="concept-link template">
                <span class="concept-link-header"></span>
                <span class="concept-link-content"><a href="#"></a></span>
                <span class="concept-link-remove-action"><input type="hidden" name="<?= $this->inputName; ?>[]" value="" /></span>                
                <span class="uri"></span>
            </li>
        </ul>
    <?php endif ?>
</span>