<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(); ?>">
    <?php echo $this->translate('First')?>
  </a> |
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('First')?></span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="?page=<?php echo $this->previous; ?>">
    &lt; <?php echo $this->translate('Previous')?>
  </a> |
<?php else: ?>
  <span class="disabled">&lt; <?php echo $this->translate('Previous')?></span> |
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="?page=<?php echo $page; ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="?page=<?php echo $this->next; ?>">
    <?php echo $this->translate('Next')?> &gt;
  </a> |
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('Next')?> &gt;</span> |
<?php endif; ?>


 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="?page=<?php echo $this->last; ?>">
    <?php echo $this->translate('Last')?>
  </a>
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('Last')?></span>
<?php endif; ?>
 
</div>
<?php endif; ?>