<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Alexandar Mitsev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php
$conceptSchemeOptions = json_encode($this->conceptSchemeOptions);
$profilesOptions = json_encode($this->profilesOptions);
$js = <<<JS
if (parent.onAdvancedOptionsChanged) {
	parent.onAdvancedOptionsChanged({$conceptSchemeOptions}, {$profilesOptions});
}
JS;

$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, $js);
?>