<?php
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */


$di = Zend_Controller_Front::getInstance()->getDispatcher()->getContainer();
$tenant = $this->resource;

/* @var $tenantManager \OpenSkos2\TenantManager */
$tenantManager = $di->get('OpenSkos2\TenantManager');
$code = $tenant->getCode();
$name = $tenantManager->getTenantNameByCode($code);
$this->headTitle($name);
require_once '/app/test/application/api/views/scripts/Util.php';
?>
<h2><?php echo $this->escape($name)?></h2>
<dl>
    <?php
        foreach ($this->resProperties as $key => $val): ?>
         <dt><?php echo  $key?>:</dt>
        <?php if ($key==="type"):?>
	 <dd><a rel="external" href="<?=$val ?>"><?php echo $val?></a></dd>
         <?php endif?>
         <?php if ($key!=="type"):?>
	 <dd><?php echo $val?></dd>
         <?php endif?>
        <?php endforeach;?>
</dl>
<h3><?php echo $this->translate('Sets')?></h3>
<?php 
	$sets = $tenantManager->fetchSetsForTenant($code);
?>
<ul id="sets-per-institute">
<?php foreach ($sets as $seturi => $props):?>
    <li>
        <?php if (isset($props['openskos_code'])):?>
	<p class="dc_title"><a href="<?php echo $this->url(array('controller'=>'set', 'id' => $props['openskos_code']))?>.html">
         <?php echo $props['dcterms_title']?></a></p>
        <?php else:?>
        <p class="dc_title"><?php echo $props['dcterms_title']?></p>
        <?php endif?>
	<?php if (isset($props['dcterms_description'])):?>
		<p class="dc_description"><?php echo nl2br($props['dcterms_description'], true)?></p>
	<?php endif?>
	<?php if (isset($props['openskos_webpage'])):?>
		<p class="website"><?php echo $this->translate('See')?> <a rel="external" href="<?php echo $props['openskos_webpage']?>"><?php echo $props['openskos_webpage']?></a></p>
	<?php endif?>
	</li>
<?php endforeach?>
        
</ul>
<h3>Alternative formats</h3>
<ul>
    <li><a class="json" href="<?php echo Util::switchFromHtmlToOtherFormat('json', $this->url())?>">JSON</a></li>
	<li><a class="jsonp" href="<?php echo Util::switchFromHtmlToOtherFormat('jsonp', $this->url(),'myCallback123')?>">JSONP</a></li>
	<li><a class="rdf" href="<?php echo Util::switchFromHtmlToOtherFormat('rdf', $this->url())?>">RDF</a></li>
</ul>
