<?php
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle ($this->translate('Institutions'))?>
<h2><?php echo $this->translate('Institutions')?></h2>
<p>These are the avaliable institutions in this repository:</p>
<ul>
	<?php foreach ($this->tenants as $tenant):?>
	<li>
		<a href="<?php echo $this->url(array('id' => $tenant->code), 'rest')?>.html">
			<strong><?php echo $tenant->name?></strong>
		</a>
	</li>
	<?php endforeach?>
</ul>
<h3>Alternative formats</h3>
<ul>
	<li><a class="json" href="<?php echo $this->url()?>?format=json">JSON</a></li>
	<li><a class="jsonp" href="<?php echo $this->url()?>?format=jsonp&callback=myCallback_1234">JSONP</a></li>
	<li><a class="rdf" href="<?php echo $this->url()?>">RDF</a></li>
</ul>
