<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2012 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Alexandar Mitsev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php if ($this->renderHeader):?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'?>
	<rdf:RDF<?php foreach ($this->namespaces as $prefix => $uri):?> xmlns:<?php echo $prefix?>="<?php echo $uri?>"<?php endforeach ?>>
<?php endif?>

<?php if ($this->renderBody):?>
	<?php foreach ($this->data as $concept):?>
		<?php echo $concept['xml']?>
	<?php endforeach ?>
<?php endif?>

<?php if ($this->renderFooter):?>
	</rdf:RDF>
<?php endif?>
