<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Manage collections'))?>

<p><a href="<?php echo $this->url(array('action' => 'edit'))?>"><?php echo $this->translate('Create a new Collection')?>&raquo;</a></p>
<?php if (!count($this->collections)):?>
<div class="note">
	<p><?php echo $this->translate('No collections to manage.')?></p>
</div>
<?php else:?>
<p><?php echo $this->translate('Click on a code to edit the collection.')?></p>
<table class="collections">
	<thead>
		<tr>
			<th>#</th>
			<th><?php echo $this->translate('Code')?></th>
			<th><?php echo $this->translate('Title')?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->collections as $i => $collection):?>
		<tr class="<?php echo $i % 2 ? 'even' : 'uneven'?>">
			<th scope="row"><?php echo $i+1?></th>
			<td><a href="<?php echo $this->url(array('action' => 'edit', 'collection' => $collection->code))?>"><?php echo $collection->code?></a></td>
			<td><?php echo $collection->dc_title?></td>
		</tr>
		<?php endforeach?>
	</tbody>
</table>
<?php endif?>

