<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php 
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>
<ul id="dashboard-menu" class="box">
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'index'), null, true)?>" <?php if ($controller === 'index') echo 'class="active"'?>><?php echo $this->translate('Dashboard')?></a></li>
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'institution'), null, true)?>" <?php if ($controller === 'institution') echo 'class="active"'?>><?php echo $this->translate('Manage institution')?></a></li>
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'collections'), null, true)?>" <?php if ($controller === 'collections') echo 'class="active"'?>><?php echo $this->translate('Manage collections')?></a></li>
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'users'), null, true)?>" <?php if ($controller === 'users') echo 'class="active"'?>><?php echo $this->translate('Manage users')?></a></li>
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'jobs'), null, true)?>" <?php if ($controller === 'jobs') echo 'class="active"'?>><?php echo $this->translate('Manage jobs')?></a></li>
</ul>
<div class="clear"></div>