<ul id="dashboard-menu">
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'institution'), null, true)?>"><?php echo $this->translate('Manage institution')?></a></li>
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'collections'), null, true)?>"><?php echo $this->translate('Manage collections')?></a></li>
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'users'), null, true)?>"><?php echo $this->translate('Manage users')?></a></li>
	<li><a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'api-keys'), null, true)?>"><?php echo $this->translate('Manage API keys')?></a></li>
</ul>