<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>

<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd"
	     xmlns:dc="http://dublincore.org/documents/dcmi-namespace/"
	     xmlns:dcterms="http://purl.org/dc/terms/"
	     >
 <responseDate><?php echo $this->responseDate?></responseDate>
 <request
 	<?php foreach ($this->oai->getParams(true) as $key => $value):?>
 	<?php echo $key?>="<?php echo $value instanceof Zend_Date ? $value->toString(Zend_Date::ISO_8601) : $value?>"
 	<?php endforeach?>><?php echo $this->baseUrl?></request> 
 <?php echo $this->oai?>
</OAI-PMH>      
