<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<ListSets>
<?php foreach ($this->tenants as $tenant):
	$rdf = $tenant->toRdf();
?>
  <set>
    <setSpec><?php echo $tenant->code?></setSpec>
    <setName><?php echo $this->escape($tenant->name)?></setName>
    <setDescription>
    	<?php echo $rdf->saveXml($rdf->documentElement)?>
    </setDescription>
  </set>
  <?php if (isset($this->collections[$tenant->code])):?>
    <?php foreach ($this->collections[$tenant->code] as $collection):
    	$rdf = $collection->toRdf();
    ?>
      <set>
        <setSpec><?php echo $tenant->code?>:<?php echo $collection->code?></setSpec>
        <setName><?php echo $this->escape($collection->dc_title)?></setName>
        <setDescription>
        	<?php echo $rdf->saveXml($rdf->documentElement)?>
        </setDescription>
      </set>
    <?php endforeach?>
    <?php if (isset($this->conceptSchemes[$collection->id])):?>
        <?php foreach ($this->conceptSchemes[$collection->id] as $conceptScheme):
        ?>
      <set>
        <setSpec><?php echo $tenant->code?>:<?php echo $collection->code?>:<?php echo $conceptScheme['uuid']?></setSpec>
        <setName><?php echo $this->escape($conceptScheme['dc_title']?$conceptScheme['dc_title']:$conceptScheme['uri'])?></setName>
      </set>
        <?php endforeach?>
    <?php endif?>
  <?php endif?>
<?php endforeach?>
</ListSets>