<?php 
/**
 * OpenSKOS
*
* LICENSE
*
* This source file is subject to the GPLv3 license that is bundled
* with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.gnu.org/licenses/gpl-3.0.txt
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@zend.com so we can send you a copy immediately.
*
* @category   OpenSKOS
* @package    OpenSKOS
* @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
* @author     Mark Lindeman
* @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
*/
?>
<?php if ($this->parameters['verb']=='ListIdentifiers' && 0 === count($this->data)):?>
    <error code="noRecordsMatch">The combination of the values of the from, until, set and metadataPrefix arguments results in an empty list.</error>
<?php return; endif; ?>
<ListIdentifiers>
<?php foreach ($this->data as $doc):?>
	<?php echo $this->partial('index/partial.header.phtml', array('doc' => $doc, 'conceptSchemes' => $this->conceptSchemes))?>
<?php endforeach?>
<?php echo $this->render('index/resumptionToken.phtml')?>
</ListIdentifiers>
