<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<ListSets>
<?php foreach ($this->tenants as $tenant):
?>
  <set>
    <setSpec><?php echo $tenant->code?></setSpec>
    <setName><?php echo $this->escape($tenant->name)?></setName>
  </set>
  <?php if (isset($this->collections[$tenant->code])):?>
    <?php foreach ($this->collections[$tenant->code] as $collection): ?>
      <set>
        <setSpec><?php echo $tenant->code?>:<?php echo $collection->code?></setSpec>
        <setName><?php echo $this->escape($collection->dc_title)?></setName>
        <?php if ($collection->dc_description):?>
        <setDescription>
         <oai_dc:dc 
              xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" 
              xmlns:dc="http://purl.org/dc/elements/1.1/" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ 
              http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
              <dc:description><?php echo $this->escape($collection->dc_description)?></dc:description>
           </oai_dc:dc>
        </setDescription>
        <?php endif?>
      </set>
    <?php if (isset($this->conceptSchemes[$tenant->code][$collection->id])):?>
        <?php foreach ($this->conceptSchemes[$tenant->code][$collection->id] as $conceptScheme): ?>
      <set>
        <setSpec><?php echo $tenant->code?>:<?php echo $collection->code?>:<?php echo $conceptScheme['uuid']?></setSpec>
        <setName><?php echo $this->escape(isset($conceptScheme['dcterms_title']) ? $conceptScheme['dcterms_title'][0] : $conceptScheme['uri'])?></setName>
      </set>
        <?php endforeach?>
    <?php endif?>
  <?php endforeach?>
    <?php endif?>
<?php endforeach?>
</ListSets>