<?php require_once APPLICATION_PATH . '/api/models/Concept.php'?>
<<?php echo $this->parameters['verb']?>>
<?php foreach ($this->data as $doc):?>
<record>
	<?php echo $this->partial('index/partial.header.phtml', array('doc' => $doc))?>
	<metadata>
		<?php if ($this->metadataPrefix === 'oai_rdf'):?>
		<?php 
			//get all namespaces from this collection:
		?>
		<rdf:RDF
			xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" 
			<?php foreach ($this->namespacesByCollection[$doc['collection']] as $ns):
			?>
	         xmlns:<?php echo $ns['prefix']?>="<?php echo $ns['uri']?>" 
			<?php endforeach?>
		>
		<?php echo $doc['xml']?>
		</rdf:RDF>
		<?php else:?>
		<oai_dc:dc 
		         xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" 
		         xmlns:dc="http://purl.org/dc/elements/1.1/" 
		<?php if ($this->count==0):?>
		         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		         xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ 
		         http://www.openarchives.org/OAI/2.0/oai_dc.xsd"
		<?php endif?>>
		<dc:title><?php echo $this->escape($doc['prefLabel'][0])?></dc:title>
		<dc:identifier><?php echo $this->escape($doc['uri'])?></dc:identifier>
		<dc:type>http://www.w3.org/2004/02/skos/core#<?php echo $this->escape($doc['class'])?></dc:type>
		<dc:source><?php echo $this->escape($doc['uri'])?></dc:source>
		</oai_dc:dc>
		<?php endif?>
	</metadata>
</record>
<?php endforeach?>
<?php
if ($this->parameters['verb']!='GetRecord'):
	echo $this->render('index/resumptionToken.phtml');
endif;
?>
</<?php echo $this->parameters['verb']?>>
