<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php require_once APPLICATION_PATH . '/api/models/Concept.php'?>
<?php if ($this->parameters['verb']=='ListRecords' && 0 === count($this->data)):?>
    <error code="noRecordsMatch">The combination of the values of the from, until, set and metadataPrefix arguments results in an empty list.</error>
<?php return; endif; ?>
<<?php echo $this->parameters['verb']?>>
<?php foreach ($this->data as $doc):
    if (!isset($doc['deleted'])) $doc['deleted'] = false;

	$isDeleted = (true === $doc['deleted'] || (isset($doc['status']) && $doc['status'] == 'expired'));
?>
<record>
	<?php echo $this->partial('index/partial.header.phtml', array('doc' => $doc, 'collections' => $this->collections, 'conceptSchemes' => $this->conceptSchemes))?>
	<?php if ( ! $isDeleted):?>
	<metadata>
		<?php if ($this->metadataPrefix === 'oai_rdf'):?>
		<?php 
			//get all namespaces from this collection:
		?>
		<rdf:RDF
			xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" 
            xmlns:skos="http://www.w3.org/2004/02/skos/core#" 
            <?php if (isset($this->namespacesByCollection[$doc['collection']])):?>
                <?php foreach ($this->namespacesByCollection[$doc['collection']] as $ns):
                    if (in_array($ns['prefix'], array('rdf', 'skos'))) continue;
                ?>
                 xmlns:<?php echo $ns['prefix']?>="<?php echo $ns['uri']?>" 
                <?php endforeach?>
            <?php endif?>
		>
		<?php echo $doc['xml']?>
		</rdf:RDF>
		<?php else:?>
		<oai_dc:dc 
		         xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" 
		         xmlns:dc="http://purl.org/dc/elements/1.1/" 
		<?php if ($this->count==0):?>
		         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		         xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ 
		         http://www.openarchives.org/OAI/2.0/oai_dc.xsd"
		<?php endif?>>
		<dc:title><?php echo $this->escape($doc['class'] == 'Concept' ? $doc['prefLabel'][0] : $doc['dcterms_title'][0])?></dc:title>
		<dc:identifier><?php echo $this->escape($doc['uri'])?></dc:identifier>
		<dc:type>http://www.w3.org/2004/02/skos/core#<?php echo $this->escape($doc['class'])?></dc:type>
		<dc:source><?php echo $this->escape($doc['uri'])?></dc:source>
		</oai_dc:dc>
		<?php endif?>
	</metadata>
	<?php endif?>
</record>
<?php endforeach?>
<?php
if ($this->parameters['verb']!='GetRecord'):
	echo $this->render('index/resumptionToken.phtml');
endif;
?>
</<?php echo $this->parameters['verb']?>>
