<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
	<header>
		<identifier><?php echo $this->doc['uuid']?></identifier>
		<datestamp><?php echo $this->doc['timestamp']?></datestamp>
		<?php if(false && isset($this->doc['ConceptSchemes'])):?>
		<?php foreach ($this->doc['ConceptSchemes'] as $ConceptScheme):?>
		<setSpec><?php echo OpenSKOS_Solr::md5_uuid($ConceptScheme)?></setSpec>
		<?php endforeach?>
		<?php endif?>
		<setSpec><?php echo $this->doc['tenant']?></setSpec>
		<setSpec><?php echo $this->doc['tenant'].':'.$this->doc['collection']?></setSpec>
	</header>
