<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */

$collection = false;
if ($this->doc['collection']) {
    if (!isset($this->collections)) {
        $model = new OpenSKOS_Db_Table_Collections();
        $row = $model->find($this->doc['collection'])->current();
        if ($row) {
            $collection = $row->code;
        }
    } else {
        $collection = $this->collections[$this->doc['collection']]['code'];
    }
}

$isDeleted = (true === $this->doc['deleted'] || (isset($this->doc['status']) && $this->doc['status'] == 'expired'));

$dateStamp = new Zend_Date(($isDeleted && ! empty($this->doc['deleted_timestamp']) ? $this->doc['deleted_timestamp'] : $this->doc['timestamp']), Zend_Date::ISO_8601);

?>
	<header <?php if ($isDeleted) echo 'status="deleted"'?>>
		<identifier><?php echo $this->doc['uuid']?></identifier>
		<datestamp><?php echo date(OaiPmh::XS_DATETIME_FORMAT, $dateStamp->toString(Zend_Date::TIMESTAMP));?></datestamp>
		<?php if (! $isDeleted):?>
		<setSpec><?php echo $this->doc['tenant']?></setSpec>
    		<?php if ($collection):?>
		<setSpec><?php echo $this->doc['tenant'].':'.$collection?></setSpec>
        		<?php if(isset($this->doc['inScheme'])):?>
    	    	    <?php foreach ($this->doc['inScheme'] as $ConceptScheme):?>
		<setSpec><?php echo $this->doc['tenant'].':'.$collection?>:<?php echo (isset($this->conceptSchemes[$this->doc['tenant']][$ConceptScheme]) ? $this->conceptSchemes[$this->doc['tenant']][$ConceptScheme]['uuid'] : 'NA')?></setSpec>
    		        <?php endforeach?>
    		    <?php endif?>
		    <?php endif?>
	    <?php endif?>
	</header>
