<?php 
$resumptionToken = $this->oai->getResumptionToken();

if ($this->data->getCurrentPageNumber() == 1 && $this->data->getTotalItemCount() <= $this->data->getItemCountPerPage()) {
	return;
}

if (!$resumptionToken) return;
$cursor = ($this->data->getCurrentPageNumber()  - 1 ) * $this->data->getItemCountPerPage();

if (($cursor + $this->data->getItemCountPerPage()) >= $this->data->getTotalItemCount()) {
	$resumptionToken = '';
}


?>
<resumptionToken  
      completeListSize="<?php echo $this->data->getTotalItemCount()?>" 
      cursor="<?php echo $cursor?>"><?php echo $resumptionToken?></resumptionToken>
