<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php 
$resumptionToken = $this->oai->getResumptionToken();

if ($this->data->getCurrentPageNumber() == 1 && $this->data->getTotalItemCount() <= $this->data->getItemCountPerPage()) {
	return;
}

if (!$resumptionToken) return;
$cursor = ($this->data->getCurrentPageNumber()  - 1 ) * $this->data->getItemCountPerPage();

if (($cursor + $this->data->getItemCountPerPage()) >= $this->data->getTotalItemCount()) {
	$resumptionToken = '';
}


?>
<resumptionToken  
      completeListSize="<?php echo $this->data->getTotalItemCount()?>" 
      cursor="<?php echo $cursor?>"><?php echo $resumptionToken?></resumptionToken>
