<?php
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle ($this->tenant->name)?>

<h2><?php echo $this->escape($this->tenant->name)?></h2>
<dl>
	<?php foreach ($this->tenant as $key => $val): if ($key == 'name' || !$val) continue;
		switch ($key) {
			case 'email':
				$val = '<a href="mailto:' . $val.'">'.$val.'</a>';
				break;
			case 'website':
				$val = '<a href="' . $val.'">'.$val.'</a>';
				break;
			default:
				$val = $this->escape($val);
		}
	?>
	<dt><?php echo $this->translate($key)?>:</dt>
	<dd><?php echo $val?></dd>
	<?php endforeach?>
</dl>
<h3><?php echo $this->translate('Collections')?></h3>
<?php 
	$collections = $this->tenant->findDependentRowset('OpenSKOS_Db_Table_Collections');
	$conceptsPerCollection = $this->tenant->getConceptsPerCollection();
?>
<ul id="collections-per-institute">
<?php foreach ($collections as $collection):?>
	<li>
		<p class="dc_title"><a href="<?php echo $this->url(array('controller'=>'collections', 'id' => $collection->getId()))?>.html"><?php echo $collection->dc_title?> (<?php echo isset($conceptsPerCollection[$collection->id]) ? number_format($conceptsPerCollection[$collection->id], 0) : 0?> Concepts)</p>
	<?php if ($collection->dc_description):?>
		<p class="dc_description"><?php echo nl2br($collection->dc_description, true)?></p>
	<?php endif?>
	<?php if ($collection->website):?>
		<p class="website"><?php echo $this->translate('See')?> <a rel="external" href="<?php echo $collection->website?>"><?php echo $collection->website?></a></p>
	<?php endif?>
	</li>
<?php endforeach?>
</ul>
<h3>Alternative formats</h3>
<ul>
	<li><a class="json" href="<?php echo str_replace('.html', '.json', $this->url())?>">JSON</a></li>
	<li><a class="jsonp" href="<?php echo str_replace('.html', '.jsonp', $this->url())?>&callback=myCallback_1234">JSONP</a></li>
	<li><a class="rdf" href="<?php echo str_replace('.html', '.rdf', $this->url())?>">RDF</a></li>
</ul>
