<?php $this->headTitle ($this->translate('Institutions'))?>
<h2><?php echo $this->translate('Institutions')?></h2>
<p>These are the avaliable institutions in this repository:</p>
<ul>
	<?php foreach ($this->tenants as $tenant):?>
	<li>
		<a href="<?php echo $this->url(array('id' => $tenant->code), 'rest')?>.html">
			<strong><?php echo $tenant->name?></strong>
		</a>
	</li>
	<?php endforeach?>
</ul>
<h3>Alternative formats</h3>
<ul>
	<li><a class="json" href="<?php echo $this->url()?>?format=json">JSON</a></li>
	<li><a class="rdf" href="<?php echo $this->url()?>">RDF</a></li>
</ul>
