<?php $this->headTitle ($this->translate('Manage jobs'))?>
<?php echo $this->render('menu.phtml');?>
<h2><?php echo $this->translate('Manage jobs')?></h2>
<?php if (!count($this->jobs)):?>
<p><?php echo $this->translate('There are no jobs scheduled.')?></p>
<?php else:?>
<table>
	<thead>
		<tr>
			<th><?php echo $this->translate('Collection')?></th>
			<th><?php echo $this->translate('Created')?></th>
			<th><?php echo $this->translate('Created by')?></th>
			<th><?php echo $this->translate('Started')?></th>
			<th><?php echo $this->translate('Filename')?></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->jobs as $job):?>
		<tr>
			<td><?php echo $job['collection']?></td>
			<td><?php echo $job['created']?></td>
			<td><?php echo $job['user']?></td>
			<td><?php echo $job['started']?$job['started']:'-'?></td>
			<td><?php echo OpenSKOS_Db_Table_Jobs::getParam($job['parameters'], 'name')?></td>
			<td>
			<?php if(!$this->started):?>
				<a href="<?php echo $this->url(array('action' => 'view', 'job' => $job['id']))?>"><?php echo $this->translate('details')?>&raquo;</a>
			<?php else:?>
			&nbsp;
			<?php endif?>
			</td>
		</tr>
		<?php endforeach?>
	</tbody>
</table>
<?php endif?>
