<?php $this->headTitle ($this->translate('Job details'))?>
<?php echo $this->render('menu.phtml');?>
<h2><?php echo $this->translate('Job details')?></h2>
<ul>
	<li>
		<em><?php echo $this->translate('Collection')?>:</em>
		<a href="<?php echo $this->url(array('controller' => 'collections', 'action' => 'edit', 'collection' => $this->collection->code))?>"><?php echo $this->collection->dc_title?></a>
	</li>
	<li>
		<em><?php echo $this->translate('Delete before import')?>:</em>
		<?php echo $this->job->getParam('deletebeforeimport') ? $this->translate('yes') : $this->translate('no')?>
	</li>
	<li>
		<em><?php echo $this->translate('Created')?>:</em>
		<?php echo $this->job->created?>
	</li>
	<li>
		<em><?php echo $this->translate('Created by')?>:</em>
		<a href="<?php echo $this->url(array('controller' => 'users', 'action' => 'edit', 'user' => $this->user->id))?>"><?php echo $this->user->name?></a>
	</li>
	<li>
		<em><?php echo $this->translate('Started')?>:</em>
		<?php echo $this->job->started ? $this->job->started  : '-'?>
	</li>
	<li>
		<em><?php echo $this->translate('Finished')?>:</em>
		<?php echo $this->job->finished ? $this->job->finished : '-'?>
	</li>
	<li>
		<em><?php echo $this->translate('Status')?>:</em>
		<?php echo $this->job->status ? '<span class="job-status-'.strtolower($this->job->status).'">' . $this->job->status  .'</span>'  : '-'?>
	</li>
	<?php if ($this->job->info):?>
	<li>
		<em><?php echo $this->translate('Info')?>:</em>
		<?php echo $this->job->info?>
	</li>
	<?php endif?>


</ul>
<?php if ($this->job->task === OpenSKOS_Db_Table_Row_Job::JOB_TASK_IMPORT):?>
<h2><?php echo $this->translate('File details')?></h2>
<ul>
	<li>
		<em><?php echo $this->translate('Name')?>:</em>
		<?php echo $this->job->getParam('name')?>
	</li>
	<li>
		<em><?php echo $this->translate('Type')?>:</em>
		<?php echo $this->job->getParam('type')?>
	</li>
	<li>
		<em><?php echo $this->translate('Filesize')?>:</em>
		<?php echo $this->HumanFilesize($this->job->getParam('size'), 1)?>
		(<?php echo number_format($this->job->getParam('size'))?> bytes)
	</li>
</ul>
<?php elseif($this->job->task === OpenSKOS_Db_Table_Row_Job::JOB_TASK_HARVEST):?>
<h2><?php echo $this->translate('Harvest details')?></h2>
<?php 
$url = rtrim($this->job->getParam('url'),'?').'?verb=ListRecords';
if ($this->job->getParam('set')) $url .= '&set=' . $this->job->getParam('set');
if ($this->job->getParam('from')) $url .= '&from=' . $this->job->getParam('from');
if ($this->job->getParam('until')) $url .= '&until=' . $this->job->getParam('until');
?>
<ul>
	<li>
		<em><?php echo $this->translate('OAI Base URL')?>:</em>
		<?php echo $this->job->getParam('url')?>
	</li>
	<li>
		<em><?php echo $this->translate('SetSpec')?>:</em>
		<?php echo $this->job->getParam('set')?>
		<?php if ($this->job->getParam('set')):?>
		(<?php echo $this->job->getParam('setName')?>)
		<?php endif?>
	</li>
	<li>
		<em><?php echo $this->translate('From')?>:</em>
		<?php echo $this->job->getParam('from')
			? date('r', $this->job->getParam('from'))
			: '-' ?>
	</li>
	<li>
		<em><?php echo $this->translate('Until')?>:</em>
		<?php echo $this->job->getParam('until')
			? date('r', $this->job->getParam('until'))
			: '-' ?>
	</li>
</ul>
<p><?php echo $this->translate('URL used for Harvesting')?>: <a href="<?php echo $url?>" rel="external"><?php echo $this->escape($url)?></a></p>
<?php endif?>
<form method="post" action="<?php echo $this->url(array('action' => 'delete'))?>">
	<p><input type="submit" value="<?php echo $this->translate('Remove job')?>" /></p>
</form>