<?php
$baseUrl = $this->url(array(), 'default', true);
if ($baseUrl) $baseUrl = rtrim($baseUrl, '/').'/';

$lang = (string)Zend_Registry::get('Zend_Locale');

?>
<!DOCTYPE html>
<html id="top" xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $lang?>" lang="<?php echo $lang?>">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta charset=utf-8 />
		<!--[if lt IE 9]>
		<script src="<?php echo $baseUrl?>assets/scripts/html5.js"></script>
		<![endif]-->
		<script src="<?php echo $baseUrl?>assets/scripts/mootools-core-1.3.2-full-nocompat-yc.js"></script>
		<script src="<?php echo $baseUrl?>assets/scripts/mootools-more-1.3.2.1.js"></script>
		<script src="<?php echo $baseUrl?>assets/scripts/openskos.js"></script>
		<script src="<?php echo $baseUrl?>assets/scripts/forms.js"></script>
		<link rel="stylesheet" href="<?php echo $baseUrl?>assets/styles/default.css" type="text/css" media="all" />
		<link rel="stylesheet" href="<?php echo $baseUrl?>assets/styles/forms.css" type="text/css" media="screen" />
		<link rel="shortcut icon" href="<?php echo $baseUrl?>assets/images/favicon.ico" />
		<?php
    	echo $this->headMeta();
    	echo $this->headScript();
		echo $this->headTitle();
		echo $this->headLink();
	    echo $this->headStyle();
	    ?>

	</head>

	<body>
		<header>
			<h1>
				<img src="<?php echo $baseUrl?>assets/images/logo-open-skos.png" alt="OpenSKOS logo"/>
				<span>OpenSKOS: Simple Knowledge Organization System Repository</span>
			</h1>
			<?php if (Zend_Auth::getInstance()->hasIdentity()):
				$identity = Zend_Auth::getInstance()->getIdentity();
			?>
			<div id="identity">
				<?php echo $this->translate('Welcome')?> <a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'users', 'action' => 'edit', 'user' => $identity->id), 'default', true)?>"><?php echo $identity->name?></a>
				[<a href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'logout'), 'default', true)?>"><?php echo $this->translate('logout')?></a>]
			</div>
			<?php endif?>
	    </header>
	    <section id="content">
   		<?php echo $this->render('flashmessenger.phtml')?>
                <?php echo $this->layout()->content?>
		</section>
		<footer>
			<p id="colofon">
				<a href="<?php echo $baseUrl?>">OpenSKOS</a> is a <a rel="external" href="http://www.catchplus.nl/">CATCHPlus</a> project
			</p>
			<p id="copyright">
				&copy; 2011 <a href="http://www.pictura-dp.nl">Pictura Database Publishing bv</a>
			</p>
		</footer>
	</body>
</html>
