<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2011 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Mark Lindeman
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */
?>
<?php $this->headTitle($this->translate('Login for OpenSKOS Editor'))?>

<div class="login-regular">
	<?php echo $this->form;?>
</div>

<div class="login-openid">
	<?php
		$baseUrl = $this->url(array(), 'default', true);
		if ($baseUrl) $baseUrl = rtrim($baseUrl, '/').'/';
	?>
	
	<?php echo $this->translate('Or, sign up with ...')?>
	<br />
	<a class="open-id-sign-in" href="<?php echo $this->url(array('controller' => 'login', 'action' => 'openid-login'))?>?openIdIdentity=<?php echo urlencode('https://www.google.com/accounts/o8/id')?>" title="<?php $this->translate('Sign up with Google')?>">
		<img src="<?php echo $baseUrl?>assets/images/google.png" /> Google
	</a>
</div>

<div class="clear"></div>

<?php 
$js = <<<JS
window.addEvent('domready', function() {
	if ($('rememberme')) {
		$('rememberme').addEvent('change', rememberMeChange);
	}
	rememberMeChange();
});

function rememberMeChange() 
{	
	$$('a.open-id-sign-in').each(function (el) {
		var href = el.get('href');
		
		if (href.indexOf('&rememberme') < 0) {
			href += '&rememberme=1';
		}
		
		if ($('rememberme').checked) {
			href = href.replace(/&rememberme=[0|1]/, '&rememberme=1');
		} else {
			href = href.replace(/&rememberme=[0|1]/, '&rememberme=0');
		}
			
		el.set('href', href);
	});
}
JS;
$this->headScript(Zend_View_Helper_HeadScript::SCRIPT, $js);
?>