<?php 
/**
 * OpenSKOS
 *
 * LICENSE
 *
 * This source file is subject to the GPLv3 license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   OpenSKOS
 * @package    OpenSKOS
 * @copyright  Copyright (c) 2015 Pictura Database Publishing. (http://www.pictura-dp.nl)
 * @author     Alexandar Mitsev
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 */

use OpenSkos2\Namespaces\Skos;

?>

<div id="status-confirmation" class="do-not-show">
    <div class="confirmation-message"><?= $this->translate('Are you sure you want to set that status. It can not be returned.')?></div>
    
    <button class="confirmation-cancel" type="button"><?= $this->translate('Cancel')?></button>
    <button class="confirmation-ok" type="button"><?= $this->translate('Ok')?></button>
</div>

<div id="status-other-concept" class="choose-other-concept do-not-show">
    <div class="choose-message redirected"><?= $this->translate('Choose the concept to which this one is redirected.')?></div>
    <div class="choose-message obsolete"><?= $this->translate('If the concept is replaced from other concept, you can choose the other one now.')?></div>
    <div class="choose-hint"><?= $this->translate('To choose - click on a concept in the left search results or in right history/selection tabs.')?></div>
    
    <div class="chosen-concept">
        <div class="chosen-concept-text">
            <?= $this->translate('Redirected to concept')?>: <span class="chosen-concept-label">(<?= $this->translate('none')?>)</span>
        </div>
        
        <div class="choose-label-to-fill">
            <?= $this->translate('Which label to fill in the chosen concept?')?>
            <select name="labelToFill" >
                <option value="<?= Skos::ALTLABEL?>"><?= $this->translate('Alternative label')?></option>
                <option value="<?= Skos::HIDDENLABEL?>"><?= $this->translate('Hidden label')?></option>
            </select>
        </div>
    </div>
    
    <button class="choose-cancel" type="button"><?= $this->translate('Cancel')?></button>
    <button class="choose-ok" type="button"><?= $this->translate('Ok')?></button>
</div>